# Generated by Django 2.2.1 on 2019-05-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=15),
        ),
    ]
