# Generated by Django 2.2.1 on 2019-05-28 15:24

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('ibroker', '0003_auto_20190528_1212'),
    ]

    operations = [
    ]
