# Generated by Django 2.2.1 on 2019-06-22 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibroker', '0004_auto_20190528_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_stock_quote',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='ibroker.Quote'),
            preserve_default=False,
        ),
    ]
